global using System;
global using System.Threading.Tasks;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using System.ComponentModel.DataAnnotations;
global using System.Linq.Expressions;
global using jobsearch.Core.Repositories;
global using jobsearch.Core.Models.EF;
