version: '3.7'

x-environment:
    &default-environment
    POSTGRES_USER: jobsearch
    POSTGRES_PASSWORD: jobsearch
    POSTGRES_DB: jobsearch_dev

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            <<: *default-environment
        ports:
            - 5000:5000
            - 7022:7022
            - 6006:6006
        volumes:
            - ..:/workspaces
        user: jobsearch
        command: sleep infinity
    redis:
        image: "redis:6-alpine"
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - ./redis_data/:/data
    db:
        image: "postgres:14-alpine"
        restart: unless-stopped
        environment: *default-environment
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
            #- ../postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

