version: '3.7'

x-environment:
    &default-environment
    POSTGRES_USER: jobsearch
    POSTGRES_PASSWORD: jobsearch
    POSTGRES_DB: jobsearch_dev
    ASPNETCORE_ENVIRONMENT: Development
    APSNETCORE_URLS: "http://0.0.0.0:4000,https://0.0.0.0:3000"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            <<: *default-environment
        ports:
            - 4200:4200 # angular ng s
            - 3000:3000 # https dotnet run
            - 4000:4000 # http dotnet run
            - 6006:6006 # storybook
        volumes:
            - .:/workspace
        user: jobsearch
        command: sleep infinity
    redis:
        image: "redis:6-alpine"
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - ./redis_data/:/data
    db:
        image: "postgres:14-alpine"
        restart: unless-stopped
        environment: *default-environment
        ports:
            - 5432:5432
        volumes:
            - ./pg_data:/var/lib/postgresql/data
            #- ../postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
